"""Add last_activity column to users

Revision ID: d86272cb01df
Revises: 153a9d83fb95
Create Date: 2025-07-30 00:37:12.792397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd86272cb01df'
down_revision = '153a9d83fb95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('parking_lots')
    op.drop_table('parking_spots')
    op.drop_table('reservations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('spot_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('parking_timestamp', sa.DATETIME(), nullable=False),
    sa.Column('leaving_timestamp', sa.DATETIME(), nullable=True),
    sa.Column('parking_cost', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['spot_id'], ['parking_spots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parking_spots',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('lot_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['parking_lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parking_lots',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('prime_location_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('address', sa.VARCHAR(length=200), nullable=True),
    sa.Column('pin_code', sa.VARCHAR(length=10), nullable=True),
    sa.Column('number_of_spots', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('role', sa.VARCHAR(length=5), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('mobile_number', sa.VARCHAR(length=15), nullable=True),
    sa.Column('vehicle_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('vehicle_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('vehicle_brand', sa.VARCHAR(length=100), nullable=True),
    sa.Column('home_address', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile_number'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('vehicle_number')
    )
    # ### end Alembic commands ###
